### ISSUE TITLE
Page title from browser is not loading in metadata when sharing the link 

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#57] opened 2020-05-13 20:40 UTC
Right now, we are simply using the title of the resource as the title for the Browser Tab, even when the user is on any individual page of the resource. We should use the title of the resource only if the user is on the Index page, and the title of each page as the Browser Tab title when the user opens any page. 

We should also use the description of the resoure as the description for the Browser Page, so that it shows up in the metadata when sharing the link on social media

**Comment by duttakapil** [comment] 2020-05-15 08:24
We should ideally be showing the title of the Page as the title of the Browser Tab when a Page is open, and title of the resource on the Index Page. Right now, we are showing the title of the entire resource on the index page and every page.

**Comment by pbteja1998** [comment] 2020-05-15 18:07
Why's this reopened?

**Comment by duttakapil** [comment] 2020-05-15 18:19
![image](https://user-images.githubusercontent.com/6577624/82083017-a3af6400-9706-11ea-9712-481498a011bb.png)

Page title is not loading in meta data

**Comment by duttakapil** [comment] 2020-05-15 18:23
We should also ideally pull a bit of content from the page and show it in the metadata as the description. Some X number of characters maybe, if it's there

**Comment by pbteja1998** [comment] 2020-06-20 01:51
Duplicate of #173

**Closed** 2020-06-20 01:51 UTC
Labels: bug, help wanted, high priority
