### ISSUE TITLE
Show "Complete" instead of "Start Learning" on every page for logged out users

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#104] opened 2020-05-21 14:59 UTC
Right now, if a user is logged out, we are showing them "Start Learning" button on every page. Instead, we should be showing them the "Complete" button, but **redirect it to the login/registration page**. 

We should show the `Start Learning` button only on the Index page of each resource

**Comment by pbteja1998** [comment] 2020-05-21 15:32
Duplicate of #88

**Closed** 2020-05-21 15:32 UTC
