### ISSUE TITLE
Remove verification of email 

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#103] opened 2020-05-21 14:45 UTC
Currently, when a user signs up on our website, we verify their email. This is not necessary for us right now. When we have a lot of users signing up regularly to the site, we can verify their email id's

**Comment by manas2297** [comment] 2020-05-25 12:56
I would like to work on this. Is it availabe. @pbteja1998

**Comment by pbteja1998** [comment] 2020-05-25 13:00
Hey @manas2297 

@VinamerGoel has already started working on this. Let's wait for him to reply. If he doesn't reply by tomorrow, then I can assign this issue to you.

Meanwhile, please take a look at #90 and see if it interests you.

**Comment by TheDheeraj007** [comment] 2020-05-25 15:14
Hi @pbteja1998 
Can I work on this issue?

**Comment by pbteja1998** [comment] 2020-05-25 15:16
Hi @TheDheeraj007 
I just asked @VinamerGoel. He can't work on this at the moment, and @manas2297 has already started working on another issue. 

Hence, I am assigning this to you.

**Comment by pbteja1998** [comment] 2020-05-25 15:21
@TheDheeraj007 A few points to consider before you start working on this.

Add a flag `IS_EMAIL_VERIFICATION_ENABLED` in .env file and use that to disable/enable email verification.

When I say disable email verification, I meant that you should not send a mail for email verification and disable any way for requesting email verification.

In the future, if we set the flag `IS_EMAIL_VERIFICATION_ENABLED` to true, the email verification part should be enabled automatically.

**Comment by TheDheeraj007** [comment] 2020-05-25 15:23
@pbteja1998  Got it!

> @TheDheeraj007 A few points to consider before you start working on this.
> 
> Add a flag `IS_EMAIL_VERIFICATION_ENABLED` in `.env` file and use that to disable/enable email verification.
> 
> When I say disable email verification, I meant that you should not send a mail for email verification and disable any way for requesting email verification.
> 
> In the future, if we set the flag `IS_EMAIL_VERIFICATION_ENABLED` to `true`, the email verification part should be enabled automatically.

@pbteja1998 got it!

**Comment by TheDheeraj007** [comment] 2020-05-25 16:07
Hi @pbteja1998 
I'm thinking of handling the following test cases for this issue:
1) Users should not receive email confirmation/ verification mail.(If IS_EMAIL_VERIFICATION_ENABLED=false)
2) On re-login currently, unconfirmed users see "Email not yet verified" message. We should disable this.(If IS_EMAIL_VERIFICATION_ENABLED=false)
3) Currently in user profile we have a "Resend Verification Email" link. We should render the link only when IS_EMAIL_VERIFICATION_ENABLED=true 

Let me know if I need to handle any additional test cases as well.

**Comment by pbteja1998** [comment] 2020-05-25 16:12
@TheDheeraj007 
Yes, I cannot think of anything else other than those that you mentioned. Start with these, if I find something else, I will add them here later.

**Comment by TheDheeraj007** [comment] 2020-05-25 17:34
Hi @pbteja1998,
On the frontend side to handle test cases 2 and 3 as mentioned above. I can think of 3 ways of doing it:

1) Since test cases 2 and 3 depend on the flag user.confirmed. (That is, the notification for the unconfirmed users and the link to the re-confirmation mail is rendered only for user.confirmed=false.) Thus, we can essentially send response user.confirmed=true when IS_EMAIL_VERIFICATION_ENABLED=false at the backend.

2)Similar to the backend, We can have  IS_EMAIL_VERIFICATION_ENABLED at the frontend .env file as well.

3) We can create an additional GraphQL request and response field separately for the "IS_EMAIL_VERIFICATION_ENABLED" flag. Thus, we would need to put an additional UI check along with the existing user.confirmed.(I personally think this could be an overkill.)

What do you think according to you should be a better approach to go with.

**Comment by pbteja1998** [comment] 2020-05-25 20:45
@TheDheeraj007 

I like this idea. Create a graphql field `disabledOrConfirmed` in user entity. (Do not store it in db.) It should return `user.confirmed` if email verification is enabled, otherwise return true.

In the frontend, use `user.disabledOrConfirmed` everywhere instead of using `user.confirmed`.

**Comment by TheDheeraj007** [comment] 2020-05-26 06:01
@pbteja1998 
Cool! Will work on it.

**Comment by TheDheeraj007** [comment] 2020-05-26 13:38
Hi @pbteja1998 
One quick question.
You want to retain the field user.confirmed  and create additional field user.disabledOrConfirmed or we can override the former one with the latter one?
If there is no other dependency of user.confirmed then we can essentially override the same.

**Comment by pbteja1998** [comment] 2020-05-26 13:54
@TheDheeraj007 No, don't override the `confirmed` field. It is not just a field, it is also a database column. That will be the source of truth to check if email is verified or not(later).

Instead, add a new field resolver function `disabledOrConfirmed` in the `User.entity.ts` and only add `@Field` decorator to it. If you don't know how to create field resolvers, check `isPage()` method in `Section.entity.ts`.

**Comment by TheDheeraj007** [comment] 2020-05-26 14:34
**Additional test case found**
4) In Basic Settings-> email: currently we are showing tooltip regarding the user is confirmed or not. 
The tooltip should not be rendered if IS_EMAIL_VERIFICATION_ENABLED=false.

This is a bit tricky as ideally when IS_EMAIL_VERIFICATION_ENABLED=true only then we should render the tooltip. But since not we are merging IS_EMAIL_VERIFICATION_ENABLED and user.confirmed as a single flag I can't think of any way of handling this. 
@pbteja1998 any thoughts?

**Comment by pbteja1998** [comment] 2020-05-26 14:38
@TheDheeraj007 show the tooltip only when user.disabledOrConfirmed is false( which is equivalent to saying, Show the tooltip only when the feature is enabled and the user is not confirmed

**Comment by pbteja1998** [comment] 2020-05-30 18:24
Fixed in #148

**Closed by pbteja1998** 2020-05-30 18:24 UTC
Labels: good first issue, help wanted
