### ISSUE TITLE
Logo stretched out on iPhone - Safari browser

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learnplex#115] opened 2020-05-22 19:20 UTC
Right now, if the user opens the website on mobile, they see the Coderplex logo stretched out vertifically like this. This is most likely because of poor compatibility with WebKit engine on Safari. We aren't seeing this on other browsers on Mobile. 

![image](https://user-images.githubusercontent.com/6577624/82701865-8f331480-9c8e-11ea-93cd-67243626e97a.png)

This is part of our overall Mobile UI enhacement requirement. Refer to issue #20 and #19

**Comment by pbteja1998** [comment] 2020-05-22 22:04
Is this still happening? I have fixed it yesterday and closed #89? If it is still happening, reopen #89 instead of opening a duplicate issue.

**Comment by pbteja1998** [comment] 2020-05-22 22:16
Duplicate of #89. Reopening that instead.

**Closed by pbteja1998** 2020-05-22 22:16 UTC
Labels: enhancement, mobile
